// Generated by scripts/build-icons.mjs from lucide-static@1.38.0.
// Do not edit by hand — run `npm run build:icons` instead.
//
// Lucide is ISC licensed; icons derived from Feather are MIT (Cole Bemis).
// The full text of both is vendored at app/features/icon-generator/icons/LICENSE
// and credited on the tool page, which is what those licences require of us.

export type IconCategory =
  | 'basic'
  | 'action'
  | 'arrow'
  | 'file'
  | 'contact'
  | 'business'
  | 'money'
  | 'place'
  | 'transport'
  | 'device';

export type IconDefinition = {
  id: string;
  category: IconCategory;
  // The bare drawing elements, without an <svg> wrapper: the tool supplies the
  // wrapper so colour, stroke width and size come from the user's settings.
  markup: string;
  tags: string[];
};

export const ICON_CATEGORIES: IconCategory[] = [
  'basic',
  'action',
  'arrow',
  'file',
  'contact',
  'business',
  'money',
  'place',
  'transport',
  'device',
];

export const ICONS: IconDefinition[] = [
  {
    id: 'house',
    category: 'basic',
    markup:
      '<path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',
    tags: ['home', 'living', 'building', 'residence', 'architecture'],
  },
  {
    id: 'search',
    category: 'basic',
    markup:
      '<path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/>',
    tags: ['find', 'scan', 'magnifier', 'magnifying glass', 'lens', 'locate', 'explore', 'discover', 'enlarge', 'zoom'],
  },
  {
    id: 'settings',
    category: 'basic',
    markup:
      '<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/><circle cx="12" cy="12" r="3"/>',
    tags: ['cog', 'edit', 'gear', 'preferences'],
  },
  {
    id: 'user',
    category: 'basic',
    markup:
      '<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
    tags: ['person', 'account', 'contact'],
  },
  {
    id: 'bell',
    category: 'basic',
    markup:
      '<path d="M10.268 21a2 2 0 0 0 3.464 0"/><path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"/>',
    tags: ['alarm', 'notification', 'sound', 'reminder'],
  },
  {
    id: 'heart',
    category: 'basic',
    markup:
      '<path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"/>',
    tags: ['like', 'love', 'emotion', 'suit', 'playing', 'cards'],
  },
  {
    id: 'star',
    category: 'basic',
    markup:
      '<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"/>',
    tags: ['bookmark', 'favorite', 'like', 'review', 'rating'],
  },
  {
    id: 'bookmark',
    category: 'basic',
    markup:
      '<path d="M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"/>',
    tags: ['save', 'favorite', 'mark', 'label', 'attachment', 'file', 'stick', 'pin', 'read', 'clip', 'marker', 'tag'],
  },
  {
    id: 'menu',
    category: 'basic',
    markup:
      '<path d="M4 5h16"/><path d="M4 12h16"/><path d="M4 19h16"/>',
    tags: ['bars', 'navigation', 'hamburger', 'options'],
  },
  {
    id: 'layout-grid',
    category: 'basic',
    markup:
      '<rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/>',
    tags: ['app', 'home', 'start'],
  },
  {
    id: 'list',
    category: 'basic',
    markup:
      '<path d="M3 5h.01"/><path d="M3 12h.01"/><path d="M3 19h.01"/><path d="M8 5h13"/><path d="M8 12h13"/><path d="M8 19h13"/>',
    tags: ['options'],
  },
  {
    id: 'sun',
    category: 'basic',
    markup:
      '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>',
    tags: ['brightness', 'weather', 'light', 'summer'],
  },
  {
    id: 'moon',
    category: 'basic',
    markup:
      '<path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"/>',
    tags: ['dark', 'night'],
  },
  {
    id: 'plus',
    category: 'action',
    markup:
      '<path d="M5 12h14"/><path d="M12 5v14"/>',
    tags: ['add', 'new', 'increase', 'increment', 'positive', 'calculate', 'toolbar', 'crosshair', 'aim', 'target', 'scope', 'sight', 'reticule', 'maximum', 'upgrade', 'extra', '+'],
  },
  {
    id: 'minus',
    category: 'action',
    markup:
      '<path d="M5 12h14"/>',
    tags: ['subtract', 'remove', 'decrease', 'decrement', 'reduce', 'negative', 'calculate', 'line', 'divider', 'separator', 'horizontal rule', 'hr', 'html', 'markup', 'markdown', '---', 'toolbar', 'operator', 'code', 'coding', 'minimum', 'downgrade'],
  },
  {
    id: 'equal',
    category: 'action',
    markup:
      '<line x1="5" x2="19" y1="9" y2="9"/><line x1="5" x2="19" y1="15" y2="15"/>',
    tags: ['calculate', 'math', 'operator', 'assignment', 'code', '='],
  },
  {
    id: 'check',
    category: 'action',
    markup:
      '<path d="M20 6 9 17l-5-5"/>',
    tags: ['done', 'todo', 'tick', 'complete', 'task'],
  },
  {
    id: 'x',
    category: 'action',
    markup:
      '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
    tags: ['cancel', 'close', 'cross', 'delete', 'ex', 'remove', 'times', 'clear', 'math', 'multiply', 'multiplication'],
  },
  {
    id: 'circle-check',
    category: 'action',
    markup:
      '<circle cx="12" cy="12" r="10"/><path d="m16 9-5.5 5.5L8 12"/>',
    tags: ['done', 'todo', 'tick', 'complete', 'task'],
  },
  {
    id: 'circle-x',
    category: 'action',
    markup:
      '<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>',
    tags: ['cancel', 'close', 'delete', 'remove', 'times', 'clear', 'error', 'incorrect', 'wrong', 'mistake', 'failure', 'linter', 'multiply', 'multiplication'],
  },
  {
    id: 'pencil',
    category: 'action',
    markup:
      '<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/><path d="m15 5 4 4"/>',
    tags: ['rubber', 'edit', 'create', 'draw', 'sketch', 'draft', 'writer', 'writing', 'stationery', 'artist'],
  },
  {
    id: 'trash-2',
    category: 'action',
    markup:
      '<path d="M10 11v6"/><path d="M14 11v6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M3 6h18"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
    tags: ['garbage', 'delete', 'remove', 'bin'],
  },
  {
    id: 'download',
    category: 'action',
    markup:
      '<path d="M12 15V3"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/>',
    tags: ['import', 'export', 'save'],
  },
  {
    id: 'upload',
    category: 'action',
    markup:
      '<path d="M12 3v12"/><path d="m17 8-5-5-5 5"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>',
    tags: ['file'],
  },
  {
    id: 'refresh-cw',
    category: 'action',
    markup:
      '<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/>',
    tags: ['rotate', 'reload', 'rerun', 'synchronise', 'synchronize', 'arrows', 'circular', 'cycle'],
  },
  {
    id: 'copy',
    category: 'action',
    markup:
      '<rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>',
    tags: ['clone', 'duplicate', 'multiple'],
  },
  {
    id: 'filter',
    category: 'action',
    markup:
      '<path d="M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z"/>',
    tags: ['filter', 'hopper'],
  },
  {
    id: 'eye',
    category: 'action',
    markup:
      '<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/>',
    tags: ['view', 'watch', 'see', 'show', 'expose', 'reveal', 'display', 'visible', 'visibility', 'vision', 'preview', 'read'],
  },
  {
    id: 'eye-off',
    category: 'action',
    markup:
      '<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"/><path d="M14.084 14.158a3 3 0 0 1-4.242-4.242"/><path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"/><path d="m2 2 20 20"/>',
    tags: ['view', 'watch', 'see', 'hide', 'conceal', 'mask', 'hidden', 'visibility', 'vision'],
  },
  {
    id: 'link',
    category: 'action',
    markup:
      '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>',
    tags: ['chain', 'url'],
  },
  {
    id: 'log-in',
    category: 'action',
    markup:
      '<path d="m10 17 5-5-5-5"/><path d="M15 12H3"/><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/>',
    tags: ['sign in', 'arrow', 'enter', 'auth'],
  },
  {
    id: 'log-out',
    category: 'action',
    markup:
      '<path d="m16 17 5-5-5-5"/><path d="M21 12H9"/><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>',
    tags: ['sign out', 'arrow', 'exit', 'auth'],
  },
  {
    id: 'arrow-up',
    category: 'arrow',
    markup:
      '<path d="m5 12 7-7 7 7"/><path d="M12 19V5"/>',
    tags: ['forward', 'direction', 'north'],
  },
  {
    id: 'arrow-down',
    category: 'arrow',
    markup:
      '<path d="M12 5v14"/><path d="m19 12-7 7-7-7"/>',
    tags: ['backwards', 'reverse', 'direction', 'south'],
  },
  {
    id: 'arrow-left',
    category: 'arrow',
    markup:
      '<path d="m12 19-7-7 7-7"/><path d="M19 12H5"/>',
    tags: ['previous', 'back', 'direction', 'west', '<-'],
  },
  {
    id: 'arrow-right',
    category: 'arrow',
    markup:
      '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
    tags: ['forward', 'next', 'direction', 'east', '->'],
  },
  {
    id: 'arrow-left-right',
    category: 'arrow',
    markup:
      '<path d="M8 3 4 7l4 4"/><path d="M4 7h16"/><path d="m16 21 4-4-4-4"/><path d="M20 17H4"/>',
    tags: ['bidirectional', 'two-way', '2-way', 'swap', 'switch', 'transaction', 'reorder', 'move', '<-', '->'],
  },
  {
    id: 'arrow-up-down',
    category: 'arrow',
    markup:
      '<path d="m21 16-4 4-4-4"/><path d="M17 20V4"/><path d="m3 8 4-4 4 4"/><path d="M7 4v16"/>',
    tags: ['bidirectional', 'two-way', '2-way', 'swap', 'switch', 'network', 'mobile data', 'internet', 'sort', 'reorder', 'move'],
  },
  {
    id: 'chevron-up',
    category: 'arrow',
    markup:
      '<path d="m18 15-6-6-6 6"/>',
    tags: ['caret', 'keyboard', 'mac', 'control', 'ctrl', 'superscript', 'exponential', 'power', 'ahead', 'fast', '^', 'dropdown'],
  },
  {
    id: 'chevron-down',
    category: 'arrow',
    markup:
      '<path d="m6 9 6 6 6-6"/>',
    tags: ['backwards', 'reverse', 'slow', 'dropdown'],
  },
  {
    id: 'chevron-left',
    category: 'arrow',
    markup:
      '<path d="m15 18-6-6 6-6"/>',
    tags: ['back', 'previous', 'less than', 'fewer', 'menu', '<'],
  },
  {
    id: 'chevron-right',
    category: 'arrow',
    markup:
      '<path d="m9 18 6-6-6-6"/>',
    tags: ['forward', 'next', 'more than', 'greater', 'menu', 'code', 'coding', 'command line', 'terminal', 'prompt', 'shell', '>'],
  },
  {
    id: 'external-link',
    category: 'arrow',
    markup:
      '<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
    tags: ['outbound', 'open', 'share'],
  },
  {
    id: 'move',
    category: 'arrow',
    markup:
      '<path d="M12 2v20"/><path d="m15 19-3 3-3-3"/><path d="m19 9 3 3-3 3"/><path d="M2 12h20"/><path d="m5 9-3 3 3 3"/><path d="m9 5 3-3 3 3"/>',
    tags: ['arrows'],
  },
  {
    id: 'file',
    category: 'file',
    markup:
      '<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/><path d="M14 2v5a1 1 0 0 0 1 1h5"/>',
    tags: ['document'],
  },
  {
    id: 'file-text',
    category: 'file',
    markup:
      '<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/><path d="M14 2v5a1 1 0 0 0 1 1h5"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
    tags: ['data', 'txt', 'pdf', 'document'],
  },
  {
    id: 'file-down',
    category: 'file',
    markup:
      '<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/><path d="M14 2v5a1 1 0 0 0 1 1h5"/><path d="M12 18v-6"/><path d="m9 15 3 3 3-3"/>',
    tags: ['download', 'import', 'export'],
  },
  {
    id: 'folder',
    category: 'file',
    markup:
      '<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/>',
    tags: ['directory'],
  },
  {
    id: 'folder-open',
    category: 'file',
    markup:
      '<path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"/>',
    tags: ['directory'],
  },
  {
    id: 'image',
    category: 'file',
    markup:
      '<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>',
    tags: ['picture', 'photo'],
  },
  {
    id: 'camera',
    category: 'file',
    markup:
      '<path d="M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z"/><circle cx="12" cy="13" r="3"/>',
    tags: ['photography', 'lens', 'focus', 'capture', 'shot', 'visual', 'image', 'device', 'equipment', 'photo', 'webcam', 'video'],
  },
  {
    id: 'paperclip',
    category: 'file',
    markup:
      '<path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551"/>',
    tags: ['attachment', 'file'],
  },
  {
    id: 'clipboard',
    category: 'file',
    markup:
      '<rect width="8" height="4" x="8" y="2" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/>',
    tags: ['copy', 'paste'],
  },
  {
    id: 'printer',
    category: 'file',
    markup:
      '<path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6"/><rect x="6" y="14" width="12" height="8" rx="1"/>',
    tags: ['fax', 'office', 'device'],
  },
  {
    id: 'archive',
    category: 'file',
    markup:
      '<rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/>',
    tags: ['index', 'backup', 'box', 'storage', 'records'],
  },
  {
    id: 'database',
    category: 'file',
    markup:
      '<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/>',
    tags: ['storage', 'memory', 'container', 'tin', 'pot', 'bytes', 'servers'],
  },
  {
    id: 'package',
    category: 'file',
    markup:
      '<path d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"/><path d="M12 22V12"/><polyline points="3.29 7 12 12 20.71 7"/><path d="m7.5 4.27 9 5.15"/>',
    tags: ['box', 'container', 'storage', 'sealed', 'delivery', 'undelivered', 'unopened', 'packed', 'archive', 'zip', 'module'],
  },
  {
    id: 'mail',
    category: 'contact',
    markup:
      '<path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"/><rect x="2" y="4" width="20" height="16" rx="2"/>',
    tags: ['email', 'message', 'letter', 'unread'],
  },
  {
    id: 'phone',
    category: 'contact',
    markup:
      '<path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"/>',
    tags: ['call'],
  },
  {
    id: 'message-circle',
    category: 'contact',
    markup:
      '<path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"/>',
    tags: ['comment', 'chat', 'conversation', 'dialog', 'feedback', 'speech bubble'],
  },
  {
    id: 'send',
    category: 'contact',
    markup:
      '<path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"/><path d="m21.854 2.147-10.94 10.939"/>',
    tags: ['email', 'message', 'mail', 'paper airplane', 'paper aeroplane', 'submit'],
  },
  {
    id: 'users',
    category: 'contact',
    markup:
      '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><path d="M16 3.128a4 4 0 0 1 0 7.744"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/>',
    tags: ['group', 'people'],
  },
  {
    id: 'calendar',
    category: 'contact',
    markup:
      '<path d="M8 2v3"/><path d="M16 2v3"/><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/>',
    tags: ['date', 'month', 'year', 'event', 'birthday', 'birthdate'],
  },
  {
    id: 'clock',
    category: 'contact',
    markup:
      '<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',
    tags: ['time', 'watch', 'alarm'],
  },
  {
    id: 'map-pin',
    category: 'contact',
    markup:
      '<path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"/><circle cx="12" cy="10" r="3"/>',
    tags: ['location', 'waypoint', 'marker', 'drop'],
  },
  {
    id: 'globe',
    category: 'contact',
    markup:
      '<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>',
    tags: ['world', 'browser', 'language', 'translate'],
  },
  {
    id: 'headset',
    category: 'contact',
    markup:
      '<path d="M3 11h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-5Zm0 0a9 9 0 1 1 18 0m0 0v5a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3Z"/><path d="M21 16v2a4 4 0 0 1-4 4h-5"/>',
    tags: ['music', 'audio', 'sound', 'gaming', 'headphones', 'headset', 'call', 'center', 'phone', 'telephone', 'voip', 'video'],
  },
  {
    id: 'video',
    category: 'contact',
    markup:
      '<path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5"/><rect x="2" y="6" width="14" height="12" rx="2"/>',
    tags: ['camera', 'movie', 'film', 'recording', 'motion picture', 'camcorder', 'reel'],
  },
  {
    id: 'share-2',
    category: 'contact',
    markup:
      '<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/><line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/>',
    tags: ['network', 'connections'],
  },
  {
    id: 'briefcase',
    category: 'business',
    markup:
      '<path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/><rect width="20" height="14" x="2" y="6" rx="2"/>',
    tags: ['work', 'bag', 'baggage', 'folder'],
  },
  {
    id: 'building-2',
    category: 'business',
    markup:
      '<path d="M10 12h4"/><path d="M10 8h4"/><path d="M14 21v-3a2 2 0 0 0-4 0v3"/><path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2"/><path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16"/>',
    tags: ['business', 'company', 'enterprise', 'skyscraper', 'organisation', 'organization', 'city'],
  },
  {
    id: 'trending-up',
    category: 'business',
    markup:
      '<path d="M16 7h6v6"/><path d="m22 7-8.5 8.5-5-5L2 17"/>',
    tags: ['statistics'],
  },
  {
    id: 'chart-column',
    category: 'business',
    markup:
      '<path d="M3 3v16a2 2 0 0 0 2 2h16"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/>',
    tags: ['statistics', 'analytics', 'diagram', 'graph'],
  },
  {
    id: 'chart-pie',
    category: 'business',
    markup:
      '<path d="M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z"/><path d="M21.21 15.89A10 10 0 1 1 8 2.83"/>',
    tags: ['statistics', 'analytics', 'diagram', 'presentation'],
  },
  {
    id: 'award',
    category: 'business',
    markup:
      '<path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526"/><circle cx="12" cy="8" r="6"/>',
    tags: ['achievement', 'badge', 'rosette', 'prize', 'winner'],
  },
  {
    id: 'handshake',
    category: 'business',
    markup:
      '<path d="m11 17 2 2a1 1 0 1 0 3-3"/><path d="m14 14 2.5 2.5a1 1 0 1 0 3-3l-3.88-3.88a3 3 0 0 0-4.24 0l-.88.88a1 1 0 1 1-3-3l2.81-2.81a5.79 5.79 0 0 1 7.06-.87l.47.28a2 2 0 0 0 1.42.25L21 4"/><path d="m21 3 1 11h-2"/><path d="M3 3 2 14l6.5 6.5a1 1 0 1 0 3-3"/><path d="M3 4h8"/>',
    tags: ['agreement', 'partnership', 'deal', 'business', 'assistance', 'cooperation', 'friendship', 'union', 'terms'],
  },
  {
    id: 'lightbulb',
    category: 'business',
    markup:
      '<path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"/><path d="M9 18h6"/><path d="M10 22h4"/>',
    tags: ['idea', 'bright', 'lights'],
  },
  {
    id: 'megaphone',
    category: 'business',
    markup:
      '<path d="M11 6a13 13 0 0 0 8.4-2.8A1 1 0 0 1 21 4v12a1 1 0 0 1-1.6.8A13 13 0 0 0 11 14H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z"/><path d="M6 14a12 12 0 0 0 2.4 7.2 2 2 0 0 0 3.2-2.4A8 8 0 0 1 10 14"/><path d="M8 6v8"/>',
    tags: ['advertisement', 'announcement', 'attention', 'alert', 'loudspeaker', 'megaphone', 'notification'],
  },
  {
    id: 'lock',
    category: 'business',
    markup:
      '<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
    tags: ['security', 'password', 'secure', 'admin'],
  },
  {
    id: 'key',
    category: 'business',
    markup:
      '<path d="m2 21 9.6-9.6"/><path d="m7.5 15.5 2.3 2.3a1 1 0 0 1 0 1.4l-2.1 2.1a1 1 0 0 1-1.4 0L4 19"/><circle cx="15.5" cy="7.5" r="5.5"/>',
    tags: ['password', 'login', 'authentication', 'secure', 'unlock', 'keychain', 'key ring', 'fob'],
  },
  {
    id: 'shield-check',
    category: 'business',
    markup:
      '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/>',
    tags: ['cybersecurity', 'secured', 'safety', 'protection', 'protected', 'guardian', 'guarded', 'armored', 'armoured', 'defense', 'defence', 'defended', 'blocked', 'threat', 'prevention', 'prevented', 'antivirus', 'vigilance', 'vigilant', 'active', 'activated', 'enabled', 'detection', 'scanned', 'found', 'strength', 'strong', 'tough', 'invincible', 'invincibility', 'invulnerable', 'undamaged', 'audited', 'admin', 'verification', 'verified', 'certification', 'certified', 'tested', 'passed', 'qualified', 'cleared', 'cleaned', 'disinfected', 'uninfected', 'task', 'completed', 'todo', 'done', 'ticked', 'checked', 'crest', 'bravery'],
  },
  {
    id: 'info',
    category: 'business',
    markup:
      '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>',
    tags: ['about', 'advice', 'clue', 'details', 'help', 'hint', 'indicator', 'information', 'knowledge', 'notice', 'status', 'support', 'tooltip'],
  },
  {
    id: 'triangle-alert',
    category: 'business',
    markup:
      '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
    tags: ['warning', 'alert', 'danger', 'exclamation mark', 'linter'],
  },
  {
    id: 'circle-help',
    category: 'business',
    markup:
      '<circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><path d="M12 17h.01"/>',
    tags: ['question mark'],
  },
  {
    id: 'zap',
    category: 'business',
    markup:
      '<path d="M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z"/>',
    tags: ['flash', 'camera', 'lightning', 'electricity', 'energy', 'power', 'quick'],
  },
  {
    id: 'japanese-yen',
    category: 'money',
    markup:
      '<path d="M12 9.5V21m0-11.5L6 3m6 6.5L18 3"/><path d="M6 15h12"/><path d="M6 11h12"/>',
    tags: ['currency', 'money', 'payment'],
  },
  {
    id: 'dollar-sign',
    category: 'money',
    markup:
      '<line x1="12" x2="12" y1="2" y2="22"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>',
    tags: ['currency', 'money', 'payment'],
  },
  {
    id: 'euro',
    category: 'money',
    markup:
      '<path d="M4 10h12"/><path d="M4 14h9"/><path d="M19 6a7.7 7.7 0 0 0-5.2-2A7.9 7.9 0 0 0 6 12c0 4.4 3.5 8 7.8 8 2 0 3.8-.8 5.2-2"/>',
    tags: ['currency', 'money', 'payment'],
  },
  {
    id: 'credit-card',
    category: 'money',
    markup:
      '<rect width="20" height="14" x="2" y="5" rx="2"/><line x1="2" x2="22" y1="10" y2="10"/>',
    tags: ['bank', 'purchase', 'payment', 'cc'],
  },
  {
    id: 'wallet',
    category: 'money',
    markup:
      '<path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1"/><path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4"/>',
    tags: ['money', 'finance', 'pocket'],
  },
  {
    id: 'banknote',
    category: 'money',
    markup:
      '<rect width="20" height="12" x="2" y="6" rx="2"/><circle cx="12" cy="12" r="2"/><path d="M6 12h.01M18 12h.01"/>',
    tags: ['currency', 'money', 'payment'],
  },
  {
    id: 'coins',
    category: 'money',
    markup:
      '<path d="M13.744 17.736a6 6 0 1 1-7.48-7.48"/><path d="M15 6h1v4"/><path d="m6.134 14.768.866-.5 2 3.464"/><circle cx="16" cy="8" r="6"/>',
    tags: ['money', 'cash', 'finance', 'gamble'],
  },
  {
    id: 'piggy-bank',
    category: 'money',
    markup:
      '<path d="M11 17h3v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3a3.16 3.16 0 0 0 2-2h1a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-1a5 5 0 0 0-2-4V3a4 4 0 0 0-3.2 1.6l-.3.4H11a6 6 0 0 0-6 6v1a5 5 0 0 0 2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1z"/><path d="M16 10h.01"/><path d="M2 8v1a2 2 0 0 0 2 2h1"/>',
    tags: ['money', 'savings'],
  },
  {
    id: 'receipt',
    category: 'money',
    markup:
      '<path d="M12 17V7"/><path d="M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8"/><path d="M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z"/>',
    tags: ['bill', 'voucher', 'slip', 'check', 'counterfoil', 'currency', 'dollar', 'usd', '$'],
  },
  {
    id: 'calculator',
    category: 'money',
    markup:
      '<rect width="16" height="20" x="4" y="2" rx="2"/><line x1="8" x2="16" y1="6" y2="6"/><line x1="16" x2="16" y1="14" y2="18"/><path d="M16 10h.01"/><path d="M12 10h.01"/><path d="M8 10h.01"/><path d="M12 14h.01"/><path d="M8 14h.01"/><path d="M12 18h.01"/><path d="M8 18h.01"/>',
    tags: ['count', 'calculating machine'],
  },
  {
    id: 'percent',
    category: 'money',
    markup:
      '<line x1="19" x2="5" y1="5" y2="19"/><circle cx="6.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/>',
    tags: ['percentage', 'modulo', 'modulus', 'remainder', '%', 'sale', 'discount', 'offer', 'marketing'],
  },
  {
    id: 'shopping-cart',
    category: 'money',
    markup:
      '<path d="m2.05 2.05 1.099-.028a1 1 0 0 1 1.008.815l2.69 14.347A1 1 0 0 0 7.83 18H18"/><path d="M4.563 5h16.435a1 1 0 0 1 .981 1.204l-1.026 6.226A2 2 0 0 1 18.962 14H6.25"/><circle cx="18" cy="20" r="2"/><circle cx="8" cy="20" r="2"/>',
    tags: ['trolley', 'cart', 'basket', 'e-commerce', 'store', 'purchase', 'products', 'items', 'ingredients'],
  },
  {
    id: 'landmark',
    category: 'place',
    markup:
      '<path d="M10 18v-7"/><path d="M11.119 2.205a2 2 0 0 1 1.762 0l7.84 3.846A.5.5 0 0 1 20.5 7h-17a.5.5 0 0 1-.22-.949z"/><path d="M14 18v-7"/><path d="M18 18v-7"/><path d="M3 22h18"/><path d="M6 18v-7"/>',
    tags: ['bank', 'building', 'capitol', 'finance', 'money', 'museum', 'art gallery', 'hall', 'institute', 'pediment', 'portico', 'doric', 'columns', 'pillars', 'classical', 'architecture', 'government', 'institution', 'monument', 'site', 'history', 'historic', 'library', 'temple', 'ancient', 'structure'],
  },
  {
    id: 'graduation-cap',
    category: 'place',
    markup:
      '<path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/><path d="M22 10v6"/><path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/>',
    tags: ['school', 'university', 'learn', 'study', 'mortarboard', 'education', 'ceremony', 'academic', 'hat', 'diploma', 'bachlor\'s', 'master\'s', 'doctorate'],
  },
  {
    id: 'school',
    category: 'place',
    markup:
      '<path d="M14 21v-3a2 2 0 0 0-4 0v3"/><path d="M18 4.933V21"/><path d="m4 6 7.106-3.79a2 2 0 0 1 1.788 0L20 6"/><path d="m6 11-3.52 2.147a1 1 0 0 0-.48.854V19a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5a1 1 0 0 0-.48-.853L18 11"/><path d="M6 4.933V21"/><circle cx="12" cy="9" r="2"/>',
    tags: ['building', 'education', 'childhood', 'university', 'learning', 'campus', 'scholar', 'student', 'lecture', 'degree', 'course', 'academia', 'study', 'knowledge', 'classroom', 'research', 'diploma', 'graduation', 'professor', 'tutorial', 'homework', 'assignment', 'exam'],
  },
  {
    id: 'hospital',
    category: 'place',
    markup:
      '<path d="M12 7v4"/><path d="M14 21v-3a2 2 0 0 0-4 0v3"/><path d="M14 9h-4"/><path d="M18 11h2a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2h2"/><path d="M18 21V5a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16"/>',
    tags: ['infirmary', 'sanatorium', 'healthcare', 'doctor', 'hospice', 'clinic', 'emergency room', 'ward', 'building', 'medical', 'vet'],
  },
  {
    id: 'store',
    category: 'place',
    markup:
      '<path d="M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5"/><path d="M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244"/><path d="M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05"/>',
    tags: ['shop', 'supermarket', 'stand', 'boutique', 'building'],
  },
  {
    id: 'building',
    category: 'place',
    markup:
      '<path d="M12 10h.01"/><path d="M12 14h.01"/><path d="M12 6h.01"/><path d="M16 10h.01"/><path d="M16 14h.01"/><path d="M16 6h.01"/><path d="M8 10h.01"/><path d="M8 14h.01"/><path d="M8 6h.01"/><path d="M9 22v-3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3"/><rect x="4" y="2" width="16" height="20" rx="2"/>',
    tags: ['organisation', 'organization'],
  },
  {
    id: 'factory',
    category: 'place',
    markup:
      '<path d="M12 16h.01"/><path d="M16 16h.01"/><path d="M3 19a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8.5a.5.5 0 0 0-.769-.422l-4.462 2.844A.5.5 0 0 1 15 10.5v-2a.5.5 0 0 0-.769-.422L9.77 10.922A.5.5 0 0 1 9 10.5V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2z"/><path d="M8 16h.01"/>',
    tags: ['building', 'business', 'energy', 'industry', 'manufacture', 'sector'],
  },
  {
    id: 'warehouse',
    category: 'place',
    markup:
      '<path d="M18 21V10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v11"/><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 1.132-1.803l7.95-3.974a2 2 0 0 1 1.837 0l7.948 3.974A2 2 0 0 1 22 8z"/><path d="M6 13h12"/><path d="M6 17h12"/>',
    tags: ['storage', 'storehouse', 'depot', 'depository', 'repository', 'stockroom', 'logistics', 'building'],
  },
  {
    id: 'hotel',
    category: 'place',
    markup:
      '<path d="M10 22v-6.57"/><path d="M12 11h.01"/><path d="M12 7h.01"/><path d="M14 15.43V22"/><path d="M15 16a5 5 0 0 0-6 0"/><path d="M16 11h.01"/><path d="M16 7h.01"/><path d="M8 11h.01"/><path d="M8 7h.01"/><rect x="4" y="2" width="16" height="20" rx="2"/>',
    tags: ['building', 'hostel', 'motel', 'inn'],
  },
  {
    id: 'utensils',
    category: 'place',
    markup:
      '<path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"/><path d="M7 2v20"/><path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"/>',
    tags: ['fork', 'knife', 'cutlery', 'flatware', 'tableware', 'silverware', 'food', 'restaurant', 'meal', 'breakfast', 'dinner', 'supper'],
  },
  {
    id: 'car',
    category: 'transport',
    markup:
      '<path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2"/><circle cx="7" cy="17" r="2"/><path d="M9 17h6"/><circle cx="17" cy="17" r="2"/>',
    tags: ['vehicle', 'drive', 'trip', 'journey'],
  },
  {
    id: 'bus',
    category: 'transport',
    markup:
      '<path d="M8 6v6"/><path d="M15 6v6"/><path d="M2 12h19.6"/><path d="M18 18h3s.5-1.7.8-2.8c.1-.4.2-.8.2-1.2 0-.4-.1-.8-.2-1.2l-1.4-5C20.1 6.8 19.1 6 18 6H4a2 2 0 0 0-2 2v10h3"/><circle cx="7" cy="18" r="2"/><path d="M9 18h5"/><circle cx="16" cy="18" r="2"/>',
    tags: ['bus', 'vehicle', 'transport', 'trip'],
  },
  {
    id: 'train-front',
    category: 'transport',
    markup:
      '<path d="M8 3.1V7a4 4 0 0 0 8 0V3.1"/><path d="m9 15-1-1"/><path d="m15 15 1-1"/><path d="M9 19c-2.8 0-5-2.2-5-5v-4a8 8 0 0 1 16 0v4c0 2.8-2.2 5-5 5Z"/><path d="m8 19-2 3"/><path d="m16 19 2 3"/>',
    tags: ['railway', 'metro', 'subway', 'underground', 'high-speed', 'bullet', 'fast', 'track', 'line'],
  },
  {
    id: 'plane',
    category: 'transport',
    markup:
      '<path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z"/>',
    tags: ['plane', 'trip', 'airplane'],
  },
  {
    id: 'bike',
    category: 'transport',
    markup:
      '<circle cx="18.5" cy="17.5" r="3.5"/><circle cx="5.5" cy="17.5" r="3.5"/><circle cx="15" cy="5" r="1"/><path d="M12 17.5V14l-3-3 4-3 2 3h2"/>',
    tags: ['bicycle', 'transport', 'trip'],
  },
  {
    id: 'ship',
    category: 'transport',
    markup:
      '<path d="M12 2v2"/><path d="M12 9.189V13"/><path d="M19 12V6a2 2 0 00-2-2H7a2 2 0 00-2 2v6"/><path d="M19.38 19A11.6 11.6 0 0021 13l-8.188-3.639a2 2 0 00-1.624 0L3 13.001a11.6 11.6 0 002.81 7.76"/><path d="M2 20c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1s1.2 1 2.5 1c2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/>',
    tags: ['boat', 'knots', 'nautical mile', 'maritime', 'sailing', 'yacht', 'cruise', 'ocean liner', 'tanker', 'vessel', 'navy', 'trip', 'releases'],
  },
  {
    id: 'truck',
    category: 'transport',
    markup:
      '<path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2"/><path d="M15 18H9"/><path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14"/><circle cx="17" cy="18" r="2"/><circle cx="7" cy="18" r="2"/>',
    tags: ['delivery', 'van', 'shipping', 'haulage', 'lorry'],
  },
  {
    id: 'fuel',
    category: 'transport',
    markup:
      '<path d="M14 13h2a2 2 0 0 1 2 2v2a2 2 0 0 0 4 0v-6.998a2 2 0 0 0-.59-1.42L18 5"/><path d="M14 21V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v16"/><path d="M2 21h13"/><path d="M3 9h11"/>',
    tags: ['filling-station', 'gas', 'petrol', 'tank'],
  },
  {
    id: 'map',
    category: 'transport',
    markup:
      '<path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z"/><path d="M15 5.764v15"/><path d="M9 3.236v15"/>',
    tags: ['location', 'navigation', 'travel'],
  },
  {
    id: 'navigation',
    category: 'transport',
    markup:
      '<polygon points="3 11 22 2 13 21 11 13 3 11"/>',
    tags: ['location', 'travel'],
  },
  {
    id: 'smartphone',
    category: 'device',
    markup:
      '<rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/>',
    tags: ['phone', 'cellphone', 'device', 'screen'],
  },
  {
    id: 'tablet',
    category: 'device',
    markup:
      '<rect width="16" height="20" x="4" y="2" rx="2" ry="2"/><line x1="12" x2="12.01" y1="18" y2="18"/>',
    tags: ['device'],
  },
  {
    id: 'laptop',
    category: 'device',
    markup:
      '<path d="M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z"/><path d="M20.054 15.987H3.946"/>',
    tags: ['computer', 'screen', 'remote'],
  },
  {
    id: 'monitor',
    category: 'device',
    markup:
      '<rect width="20" height="14" x="2" y="3" rx="2"/><line x1="8" x2="16" y1="21" y2="21"/><line x1="12" x2="12" y1="17" y2="21"/>',
    tags: ['tv', 'screen', 'display', 'virtual machine', 'vm'],
  },
  {
    id: 'wifi',
    category: 'device',
    markup:
      '<path d="M12 20h.01"/><path d="M2 8.82a15 15 0 0 1 20 0"/><path d="M5 12.859a10 10 0 0 1 14 0"/><path d="M8.5 16.429a5 5 0 0 1 7 0"/>',
    tags: ['connection', 'signal', 'wireless'],
  },
  {
    id: 'cloud',
    category: 'device',
    markup:
      '<path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"/>',
    tags: ['weather'],
  },
  {
    id: 'server',
    category: 'device',
    markup:
      '<rect width="20" height="8" x="2" y="2" rx="2" ry="2"/><rect width="20" height="8" x="2" y="14" rx="2" ry="2"/><line x1="6" x2="6.01" y1="6" y2="6"/><line x1="6" x2="6.01" y1="18" y2="18"/>',
    tags: ['cloud', 'storage'],
  },
  {
    id: 'cpu',
    category: 'device',
    markup:
      '<path d="M12 20v2"/><path d="M12 2v2"/><path d="M17 20v2"/><path d="M17 2v2"/><path d="M2 12h2"/><path d="M2 17h2"/><path d="M2 7h2"/><path d="M20 12h2"/><path d="M20 17h2"/><path d="M20 7h2"/><path d="M7 20v2"/><path d="M7 2v2"/><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="8" y="8" width="8" height="8" rx="1"/>',
    tags: ['processor', 'cores', 'technology', 'computer', 'chip', 'circuit', 'memory', 'ram', 'specs', 'gigahertz', 'ghz'],
  },
  {
    id: 'code',
    category: 'device',
    markup:
      '<path d="m16 18 6-6-6-6"/><path d="m8 6-6 6 6 6"/>',
    tags: ['source', 'programming', 'html', 'xml'],
  },
  {
    id: 'bot',
    category: 'device',
    markup:
      '<path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="M2 14h2"/><path d="M20 14h2"/><path d="M15 13v2"/><path d="M9 13v2"/>',
    tags: ['robot', 'ai', 'chat', 'assistant'],
  },
  {
    id: 'mouse-pointer-click',
    category: 'device',
    markup:
      '<path d="M14 4.1 12 6"/><path d="m5.1 8-2.9-.8"/><path d="m6 12-1.9 2"/><path d="M7.2 2.2 8 5.1"/><path d="M9.037 9.69a.498.498 0 0 1 .653-.653l11 4.5a.5.5 0 0 1-.074.949l-4.349 1.041a1 1 0 0 0-.74.739l-1.04 4.35a.5.5 0 0 1-.95.074z"/>',
    tags: ['click', 'select'],
  },
];
